# Generated by Django 3.0.5 on 2020-04-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_image_url',
            field=models.CharField(default='Image Url', max_length=300),
            preserve_default=False,
        ),
    ]
