# Generated by Django 3.0.5 on 2020-04-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200427_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image_url',
            field=models.TextField(),
        ),
    ]
